### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by tseemann** [lh3/tabtk#1]
Heng, could you please tag a release?

This old tarball seems to be available but not latest commit https://github.com/lh3/tabtk/archive/7109d8b.tar.gz

**Comment by sjackman** [comment]
Bump. Please tag a stable release.

**Comment by lh3** [comment]
Done! Thanks for pushing :)

**Comment by sjackman** [comment]
Thanks, Heng!
https://github.com/Homebrew/homebrew-science/pull/4239

**Comment by tseemann** [comment]
@lh3 we are very gentle pushers. we wait a year in between pokes! :-)
